### ISSUE TITLE
Add Form Newsletter or Contact in Home Page

### ISSUE THREAD

**Issue by henryraygan** [SlothTechOfficial/ClawUI#2]
The page landing for event required a component for newsletter or contact form in home

**Comment by vijaykrishna536** [comment]
I'll do it assign it to me

**Comment by vijaykrishna536** [comment]
I also have a question regarding the same. Is it required as section on homepage or a popup will also do the job?

**Comment by henryraygan** [comment]
Good question @vijaykrishna536!! 

Is the landing page, so section is good. Popup is a succes better way for send message confirmation or a change in button with load animation. 

Checkout this example:
![preview_Screen_Shot_2015-11-24_at_21 45 30](https://user-images.githubusercontent.com/28490601/66729102-cb57ea00-ee0e-11e9-928e-920b8dbb0c4a.png)

**Comment by henryraygan** [comment]
this issue is resolved in #7
