### ISSUE TITLE
Add Princing Table

### ISSUE THREAD

**Issue by henryraygan** [SlothTechOfficial/ClawUI#4]
The landing page need a component with a list three different prices for the event promotion. 

The component is a cards, foreach card need: 

- Title of ticket
- Short Description of ticket
- Price of ticket
- List benefits of ticket
- Button get of ticket 

Don't forget resalt the recommended ticket

Repect the colors and brand actual, Keep it simple!

**Comment by monzter50** [comment]
Assigned to me 🥇

**Comment by cristianKumul** [comment]
> Assigned to me 🥇

Thanks, go ahead!

**Comment by henryraygan** [comment]
Checkout this example, good luck

![image](https://user-images.githubusercontent.com/28490601/66612079-288d3a80-eb86-11e9-9c5e-66f3686c4ef8.png)

**Comment by henryraygan** [comment]
this issue is resolved in: #8
